[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lookatme.contrib.graph_easy"
version = "0.1.0"
authors = [
  { name="Igbanam", email="xigbanam@gmail.com" },
]
description = "Introduce text graphs with the Dot notation"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/igbanam/lookatme.contrib.graph_easy"
"Bug Tracker" = "https://github.com/igbanam/lookatme.contrib.graph_easy/issues"
